// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnidf33MoFkkupHQIK0RMGLDW-LAX4AIs',
    appId: '1:1084846411191:web:4106b97438e053153eac32',
    messagingSenderId: '1084846411191',
    projectId: 'laporbook-d8290',
    authDomain: 'laporbook-d8290.firebaseapp.com',
    storageBucket: 'laporbook-d8290.appspot.com',
    measurementId: 'G-XMF7N6R533',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN-541Bsz4sJdo5btju7kb1J8EixFaiBk',
    appId: '1:1084846411191:android:70a710d06e6bcbcd3eac32',
    messagingSenderId: '1084846411191',
    projectId: 'laporbook-d8290',
    storageBucket: 'laporbook-d8290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hAUJVcY3l7uKhOfngRxX1feCnCA5hHE',
    appId: '1:1084846411191:ios:89b5dd552ecc59c13eac32',
    messagingSenderId: '1084846411191',
    projectId: 'laporbook-d8290',
    storageBucket: 'laporbook-d8290.appspot.com',
    iosBundleId: 'com.example.laporBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9hAUJVcY3l7uKhOfngRxX1feCnCA5hHE',
    appId: '1:1084846411191:ios:860fdceb471f73d93eac32',
    messagingSenderId: '1084846411191',
    projectId: 'laporbook-d8290',
    storageBucket: 'laporbook-d8290.appspot.com',
    iosBundleId: 'com.example.laporBookApp.RunnerTests',
  );
}
